from helpers.objects.helpers import object_find
from common.tag.tag_obj import GITTag
from common.objects import GITObject
from helpers.refs.helpers import ref_create


def tag_create(repo, name, ref, create_tag_object=False):
    sha = object_find(repo, ref)

    if create_tag_object:
        tag = GITTag()
        tag.kvlm = dict()
        tag.kvlm[b"object"] = sha.encode()
        tag.kvlm[b"type"] = b"commit"
        tag.kvlm[b"tag"] = name.encode()
        tag.kvlm[b"tagger"] = b"Wyag <wyag@example.com>"
        tag.kvlm[None] = (
            b"A tag generated by wyag, which won't let you customize the message!\n"
        )
        tag_sha = GITObject.object_write(tag, repo)
        ref_create(repo, "tags/" + name, tag_sha)
    else:
        ref_create(repo, "/tags" + name, sha)
